# Generated by Django 5.1.4 on 2024-12-16 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultantUser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='is_booked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='availability',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='consultantUser.availability'),
        ),
    ]
