# Generated by Django 5.1.4 on 2024-12-16 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultantUser', '0002_availability_is_booked_booking_availability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='consultant',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='start_time',
        ),
        migrations.AlterField(
            model_name='booking',
            name='availability',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='consultantUser.availability'),
            preserve_default=False,
        ),
    ]
